version: '3'
services:
  web:
    container_name: imdbnator-api
    image: saikrishnadeep/fooapi:latest
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./newapi:/usr/src/app
    depends_on:
     - mongodb
    environment:
      MONGODB_HOST: imdbnator-mongodb:27017
      ELASTICSEARCH_HOST: imdbnator-elasticsearch:9200
    networks:
     - elk
  mongodb:
    container_name: imdbnator-mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - elk
  elasticsearch:
    container_name: imdbnator-elasticsearch
    image: elasticsearch:latest
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data/elastisearch:/usr/share/elasticsearch/data
    networks:
      - elk
  kibana:
    container_name: imdbnator-kibana
    image: kibana:latest
    container_name: kibana
    restart: always
    ports:
     - "5601:5601"
    volumes:
     - ./data/kibana:/usr/share/kibana/data
    depends_on:
     - elasticsearch
    networks:
      - elk
networks:
  elk:
    driver: bridge
